version: "3"
services:
  db:
    image: postgres:9.6
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
